POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer xxx

{
  "title": "Food blog",
  "author": "Kokki Kolmonen",
  "url": "www.foodblog.com",
  "likes": 3
}

###

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer xxx

{
  "title": "Movie blog",
  "author": "Roger Ebert",
  "url": "www.movieblog.com",
  "likes": 10
}

###

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer xxx

{
  "title": "Blog nobody likes",
  "author": "Writer nobody likes",
  "url": "www.zerolikesblog.com"
}

###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "testi": "Testing wrong blog"
}