POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdXJpZXJuZXN0aSIsImlkIjoiNWZlYzg5MzZhZGQzNTg3Mjk4NWM0NGIwIiwiaWF0IjoxNjA5NzgxMDU0fQ.-IISfZzUN2nsSA3JYUs2R9EBCyJoiHyRrmVfJT6RNm4

{
  "title": "Food blog",
  "author": "Kokki Kolmonen",
  "url": "www.foodblog.com",
  "likes": 3
}

###

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9qYXZhaXNhIiwiaWQiOiI1ZmVjODlkZmFkZDM1ODcyOTg1YzQ0YjEiLCJpYXQiOjE2MDk0MjIwMTl9.ux7Hv2OwQgMnjTr3mtHvDgrb8Fdvc_mqCSxokRq19W8

{
  "title": "Movie blog",
  "author": "Roger Ebert",
  "url": "www.movieblog.com",
  "likes": 10
}

###

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9qYXZhaXNhIiwiaWQiOiI1ZmVjODlkZmFkZDM1ODcyOTg1YzQ0YjEiLCJpYXQiOjE2MDk0MjIwMTl9.ux7Hv2OwQgMnjTr3mtHvDgrb8Fdvc_mqCSxokRq19W8

{
  "title": "Blog nobody likes",
  "author": "Writer nobody likes",
  "url": "www.zerolikesblog.com"
}

###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "testi": "Testing wrong blog"
}