POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "mauriernesti",
  "password": "topsecret"
}

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "ojavaisa",
  "password": "password2"
}